title: Frustrated Citizen
description: A place for my thoughts and writings.
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-remote-theme
navbar-links:
  About: "/about/"
  Contact: "/contact/"
